python -m src.uncertainty.inference \
    --do_validate \
    --run_name test \
    --seed 42 \
    --model Res16UNet34C \
    --val_dataset InferenceDataset \
    --data_root misc \
    --num_workers 4 \
    --weights checkpoints/finetune_100_fit_spec_0.3_PolyLR_Res16UNet34C_best.pth \
    --checkpoint_dir checkpoints \
    --eval_result_dir results/test \
    --log_dir log \
    --val_batch_size 1 